[workspace]

members = [
    "benchmark",
    "runtime",
    "simulator",
    "testModule",
    "loop_test_module",
    "struct_addition",
    "benchmark_shared_data_structures",
    "packed_i32",
    "simulator_shared_types"
]