[workspace]

members = [
    "benchmark",
    "runtime",
    "simulator",
    "testModule",
    "loop_test_module",
    "struct_addition",
    "benchmark_shared_data_structures",
    "shared_crates/packed_i32",
    "simulator_shared_types",
    "algorithims/fifo",
    "sim_modules/native/native_fifo",
    "sim_modules/wasm/wasm_fifo",
    "sim_modules/wasm_c_struct/wasm_c_fifo"
]